apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependence-visual
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dependence-visual
  template:
    metadata:
      labels:
        app: dependence-visual
    spec:
      containers:
        - name: dependence-visual
          image: archguard/dependence_visual:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: dependence-visual
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    app: dependence-visual
